apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: orderflow
data:
  NODE_ENV: "production"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "kubernetes"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq-service:5672"
  REDIS_URL: "redis://redis-service:6379"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: orderflow
data:
  REACT_APP_API_URL: "http://orderflow.local/api/v1"
  REACT_APP_ORDERS_URL: "http://orderflow.local/orders" 