apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: orderflow
  labels:
    app: rabbitmq
    tier: messaging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi 