apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  namespace: orderflow
  labels:
    app: backend-api
    tier: application
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: backend-api
  type: ClusterIP 