apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  namespace: orderflow
  labels:
    app: order-service
    tier: application
spec:
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: order-service
  type: ClusterIP 