apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: orderflow
  labels:
    app: postgres
    tier: database
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
  type: ClusterIP 