apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: orderflow
  labels:
    app: rabbitmq
    tier: messaging
spec:
  ports:
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: management
  selector:
    app: rabbitmq
  type: ClusterIP 