apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: orderflow
  labels:
    app: redis
    tier: cache
spec:
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
  type: ClusterIP 